#' Function to generate dimensions of a plot based on type.
#' @param type Type of chart.
#' @export
get_dimensions <-
  function(type = c("single","full_panel","half_panel")){

    final_type <- switch(type[1],
                         single = list(height = 6.9, width = 9.51),
                         full_panel = list(height = 15.64, width = 12.51),
                         half_panel = list(height = 11.68, width = 11.68))
    return(final_type)
  }

#' Save a plot.
#' @param plot Plot generated by ggplot2 etc.
#' @param plot_name Name of file.
#' @param type Type of chart, one of "single", "full_panel", "half_panel"
#' @export
save_plot <-
  function(plot, plot_name, dpi=600,
           type = c("single","full_panel","half_panel")){
    stopifnot(is.character(plot_name))
    stopifnot(is.character(type))
    
    stopifnot((type %in% c("single","full_panel","half_panel")))

    dims <- get_dimensions(type = type)
    wid <- dims[["width"]]
    hei <- dims[["height"]]

    ggplot2::ggsave(
      plot = plot,
      filename = paste0(plot_name, ".png"),
      dpi = dpi,
      width = wid,
      height = hei,
      units = "in")

    print(paste0(plot_name," saved"), quote = FALSE)
  }
